"""
Dry-run-first CSV import scaffold for Phase 5 bridge drills.

Purpose:
  - Read a manifest + CSV export produced by export_sqlite_to_pg.py
  - Preview the target insert order before a rehearsal import
  - Optionally load rows into an empty target database in FK-safe order

Rollback:
  - Restore the target database from backup or recreate the rehearsal target from scratch.
  - This script never mutates the source export files.

Verification:
  - Run without --execute first and confirm table order and row counts.
  - After --execute, run verify_row_parity.py against source and target.
"""

from __future__ import annotations

import argparse
import csv
from datetime import date, datetime
from decimal import Decimal
import json
from pathlib import Path
import sys

from sqlalchemy import create_engine, select, func
from sqlalchemy.sql.sqltypes import Boolean, Date, DateTime, Integer, Numeric

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import create_app
from app.core.db import db
from scripts.db_runtime_common import get_db_dialect


def _build_parser():
    parser = argparse.ArgumentParser(description="Dry-run-first CSV import scaffold for bridge drills.")
    parser.add_argument("--manifest", required=True, help="Path to manifest.json generated by export_sqlite_to_pg.py")
    parser.add_argument("--target-url", required=True, help="Target database URL")
    parser.add_argument("--execute", action="store_true", help="Actually insert rows into the target database")
    parser.add_argument(
        "--allow-nonempty",
        action="store_true",
        help="Allow import into tables that already contain rows (disabled by default)",
    )
    return parser


def _coerce_value(column, raw: str):
    if raw == "":
        return None
    if isinstance(column.type, Integer):
        return int(raw)
    if isinstance(column.type, Numeric):
        return Decimal(raw)
    if isinstance(column.type, Boolean):
        return raw.lower() == "true"
    if isinstance(column.type, DateTime):
        return datetime.fromisoformat(raw)
    if isinstance(column.type, Date):
        return date.fromisoformat(raw)
    return raw


def _load_manifest(manifest_path: Path):
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def _table_by_name():
    return {table.name: table for table in db.metadata.sorted_tables}


def _read_csv_rows(csv_path: Path, table):
    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = []
        for raw_row in reader:
            rows.append({column.name: _coerce_value(column, raw_row[column.name]) for column in table.columns})
    return rows


def main():
    args = _build_parser().parse_args()
    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        raise SystemExit(f"Manifest not found: {manifest_path}")

    app = create_app("default")
    manifest = _load_manifest(manifest_path)
    export_dir = manifest_path.parent
    target_url = args.target_url
    tables = _table_by_name()
    engine = create_engine(target_url)

    print("=" * 72)
    print("CSV Import Drill")
    print("=" * 72)
    print(f"Mode       : {'EXECUTE' if args.execute else 'DRY-RUN'}")
    print(f"Manifest   : {manifest_path}")
    print(f"Target URL : {target_url}")
    print(f"Dialect    : {get_db_dialect(target_url) or 'unknown'}")
    print("-" * 72)

    with app.app_context(), engine.begin() as conn:
        for table_name in manifest["table_order"]:
            if table_name not in tables:
                raise SystemExit(f"Unknown table in manifest: {table_name}")

            table = tables[table_name]
            csv_path = export_dir / f"{table_name}.csv"
            if not csv_path.exists():
                raise SystemExit(f"CSV file missing for table {table_name}: {csv_path}")

            rows = _read_csv_rows(csv_path, table)
            target_count = conn.execute(select(func.count()).select_from(table)).scalar_one()
            print(f"{table_name}: import_rows={len(rows)} target_existing={target_count}")

            if target_count and not args.allow_nonempty:
                raise SystemExit(
                    f"Target table '{table_name}' is not empty ({target_count} row(s)). "
                    "Use a clean rehearsal database or pass --allow-nonempty after review."
                )

            if args.execute and rows:
                conn.execute(table.insert(), rows)

    if not args.execute:
        print("-" * 72)
        print("Dry-run only. Re-run with --execute to import rows into the target database.")
        print("=" * 72)
        return

    print("-" * 72)
    print("Import complete. Run verify_row_parity.py against source and target next.")
    print("=" * 72)


if __name__ == "__main__":
    main()
